#!/bin/bash

export system=(
    '@cinnamon-desktop'
    dbus
    dbus-daemon
    dbus-tools
    dunst
    fwupd
    flatpak
    git
    gnome-keyring
    gvfs-mtp
    grim
    jmtpfs
    lxpolkit
    man-db
    man-pages
    openssh
    openssl
    papirus-icon-theme
    pipewire
    plocate
    podman
    podman-compose
    polkit
    tailscale
    wireplumber
    xdg-user-dirs
    zsh
    zsh-autosuggestions
)
export apps=(
    bc
    distrobox
    ffmpeg
    firefox
    htop
    neovim
    nvtop
    openvpn
    pavucontrol
    playerctl
    ranger
    ripgrep
    unzip
    vlc
    zip
)
export fonts=(
    cascadia-code-fonts
    fontawesome-fonts
    google-noto-emoji-fonts
)
export wifi=(
    NetworkManager
    NetworkManager-tui
    NetworkManager-wifi
    atheros-firmware
    b43-fwcutter
    b43-openfwwf
    brcmfmac-firmware
    iwlegacy-firmware
    iwlwifi-dvm-firmware
    iwlwifi-mvm-firmware
    libertas-firmware
    mt7xxx-firmware
    nxpwireless-firmware
    realtek-firmware
    tiwilink-firmware
    atmel-firmware
    zd1211-firmware
)
export all_packages=("${system[@]}" "${apps[@]}" "${fonts[@]}" "${virtualization[@]}" "${wifi[@]}")
