type: rpm-ostree
install:
  - alacritty
  - bluez-tools
  - dbus-daemon
  - dbus-tools
  - dunst
  - gnome-keyring
  - google-noto-emoji-fonts
  - grim
  - grimshot
  - lxpolkit
  - mpv
  - neovim
  - NetworkManager
  - network-manager-applet
  - papirus-icon-theme
  - pavucontrol
  - pipewire
  - playerctl
  - polkit
  - rofi-wayland
  - swayidle
  - swaylock
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - wl-clipboard
  - wlr-randr
  - wireplumber
  - xdg-user-dirs
  - xorg-x11-server-Xwayland

remove:
  - openrgb-udev-rules 
