type: rpm-ostree
install:
  - alacritty
  - ansible
  - blueman
  - bluez
  - bluez-tools
  - cascadia-code-fonts
  - dbus-daemon
  - dbus-tools
  - dunst
  - gnome-keyring
  - google-noto-emoji-fonts
  - grim
  - grimshot
  - lxpolkit
  - mpv
  - neovim
  - NetworkManager
  - NetworkManager-tui
  - papirus-icon-theme
  - pavucontrol
  - pipewire
  - playerctl
  - polkit
  - ranger
  - ripgrep
  - rofi-wayland
  - swaybg
  - swayidle
  - swaylock
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - wl-clipboard
  - wlr-randr
  - wireplumber
  - xdg-user-dirs
  - xorg-x11-server-Xwayland
  - zsh
  - zsh-autosuggestions

remove:
  - openrgb-udev-rules 
