---

name: "Build Custom Fedora Atomic Image"

permissions: 
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/'
  push:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/'
  schedule:
    - cron: '0 10 * * 0,3'  # Build at 10:00 UTC every Sunday and Wednesday. This is a few hours after base fedora images are usually updated
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  platforms: 'linux/amd64'
  registry: 'ghcr.io/areif-dev/terrafirma'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      base_version: ${{ steps.base.outputs.version }}
      tags: ${{ steps.tags.outputs.alias_tags }}
    steps:
      - name: Fetch Fedora CoreOS metadata
        id: fetch-metadata
        run: |
          echo "metadata<<EOF" >> $GITHUB_OUTPUT
          curl -s https://builds.coreos.fedoraproject.org/streams/testing.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set base version
        id: base
        run: |
          RELEASE="${{ fromJson(steps.fetch-metadata.outputs.metadata).architectures.x86_64.artifacts.metal.release }}"
          MAJOR_VERSION=$(echo $RELEASE | cut -d. -f1)
          echo "version=$MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Generate tags
        id: tags
        run: |
          TIMESTAMP="$(date +%Y%m%d)"
          TAGS="${TIMESTAMP} latest ${{ steps.base.outputs.version }}"
          echo "alias_tags=$TAGS" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Free disk space 
        run: |
          sudo rm -rf /opt/hostedtoolcache 
          sudo rm -rf /usr/local/lib/android 
          docker system prune -af 
          df -h

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          platforms: ${{ env.platforms }}
          context: ./
          image: terrafirma
          tags: ${{ needs.setup.outputs.tags }}
          containerfiles: ./Containerfile
          layers: false
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: terrafirma 
          registry: ${{ env.registry }}
          tags: ${{ needs.setup.outputs.tags }}

  sign:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v4.0.0

      - name: Sign container image
        run: |
          cosign sign -y --recursive --key env://SIGNING_SECRET ${{ env.registry }}/terrafirma@${{ needs.build.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
